"""FastAPI request models and deterministic input for Summer 2026 Demo 05."""

from __future__ import annotations

import os
from datetime import UTC, datetime, timedelta
from typing import Any, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, field_validator

from confluent_demo_common import load_dotenv_for_demo
from trip_event_contract import ServiceZone, TripEventV1

DEFAULT_TOPIC = "msds682.demo05.trip-events-api-avro.v1"
REQUEST_BASE_TIME = datetime(2026, 7, 20, 17, 0, tzinfo=UTC)
REQUEST_INTERVAL_SECONDS = 13


# ============================================================================
# KEY CONCEPT
# HTTP JSON is a boundary contract, not the Kafka event contract. FastAPI and
# Pydantic parse the request first; request_to_event() then creates TripEventV1.
# ============================================================================
class CreateTripRequest(BaseModel):
    """HTTP request contract accepted by ``POST /trip-requests``."""

    # HTTP JSON represents timestamps as strings. Parse that boundary here;
    # the resulting TripEventV1 remains the strict application model.
    model_config = ConfigDict(extra="forbid")

    request_id: str = Field(pattern=r"^request_[0-9]{4}$")
    rider_id: str = Field(pattern=r"^rider_[0-9]{3}$")
    requested_at: AwareDatetime
    zone: ServiceZone

    @field_validator("requested_at")
    @classmethod
    def normalize_requested_at(cls, value: datetime) -> datetime:
        """Normalize the HTTP timestamp before constructing the Kafka event."""

        return value.astimezone(UTC)


class TripAcceptedResponse(BaseModel):
    """Small API response; Kafka evidence remains in the secret-free report."""

    model_config = ConfigDict(extra="forbid", strict=True)

    status: Literal["accepted"]
    request_id: str
    trip_id: str
    topic: str
    delivery: Literal["local", "broker_acknowledged"]


class PublishReceipt(BaseModel):
    """Internal delivery evidence returned by a publisher implementation."""

    model_config = ConfigDict(extra="forbid", arbitrary_types_allowed=True)

    delivery: Literal["local", "broker_acknowledged"]
    topic: str
    key: str
    partition: int | None = None
    offset: int | None = None
    wire: dict[str, int] | None = None


class PublishError(RuntimeError):
    """Raised when an event cannot be accepted by the configured publisher."""


def topic_name() -> str:
    """Return the dedicated Demo 05 topic, independent of Demo 01–04 data."""

    load_dotenv_for_demo()
    return os.getenv("DEMO05_TOPIC_NAME", DEFAULT_TOPIC)


def request_to_event(request: CreateTripRequest) -> TripEventV1:
    """Map the HTTP command into Demo 05's canonical Kafka event contract."""

    trip_id = request.request_id.replace("request_", "trip_", 1)
    return TripEventV1(
        trip_id=trip_id,
        event_type="trip_requested",
        rider_id=request.rider_id,
        event_time=request.requested_at,
        zone=request.zone,
    )


# ============================================================================
# KEY CONCEPT
# Demo 05 creates its own deterministic HTTP requests. It does not read prior
# Kafka records, call another producer, or use personal data.
# ============================================================================
def deterministic_requests(
    count: int,
    *,
    seed_offset: int = 0,
) -> list[CreateTripRequest]:
    """Create bounded reproducible API requests for tests and Cloud demos."""

    if not 1 <= count <= 100:
        raise ValueError("count must be between 1 and 100")
    if not 0 <= seed_offset <= 400:
        raise ValueError("seed_offset must be between 0 and 400")

    base = REQUEST_BASE_TIME + timedelta(minutes=seed_offset)
    zones: tuple[ServiceZone, ...] = ("north", "south", "west")
    requests: list[CreateTripRequest] = []
    for index in range(count):
        request_number = 5000 + seed_offset * 10 + index
        requests.append(
            CreateTripRequest(
                request_id=f"request_{request_number:04d}",
                rider_id=f"rider_{500 + (index % 30):03d}",
                requested_at=base + timedelta(seconds=index * REQUEST_INTERVAL_SECONDS),
                zone=zones[index % len(zones)],
            )
        )
    return requests


def request_input_report(
    requests: list[CreateTripRequest],
    *,
    seed_offset: int,
) -> dict[str, Any]:
    """Describe the independent deterministic API input."""

    if not requests:
        raise ValueError("requests must not be empty")
    return {
        "source": "synthetic deterministic HTTP requests generated by Demo 05",
        "prior_demo_topic_required": False,
        "prior_kafka_data_required": False,
        "seed_offset": seed_offset,
        "count": len(requests),
        "first_request_id": requests[0].request_id,
        "last_request_id": requests[-1].request_id,
        "request_interval_seconds": REQUEST_INTERVAL_SECONDS,
    }
